module HW3.Util (funToStringBijection) where
import Data.Map (Map, fromList)
import HW3.Base (HiFun(..))

-- bijection fun to string for pretty printing and parsing
funToStringBijection :: Map HiFun String
funToStringBijection = fromList [
    (HiFunAdd, "add"),
    (HiFunDiv, "div"),
    (HiFunMul, "mul"),
    (HiFunAdd, "add"),
    (HiFunSub, "sub"),
    (HiFunNot, "not"),
    (HiFunAnd, "and"),
    (HiFunOr, "or"),
    (HiFunLessThan, "less-than"),
    (HiFunGreaterThan, "greater-than"),
    (HiFunEquals, "equals"),
    (HiFunNotLessThan, "not-less-than"),
    (HiFunNotGreaterThan, "not-greater-than"),
    (HiFunNotEquals, "not-equals"),
    (HiFunIf, "if"),
    (HiFunLength, "length"),
    (HiFunToUpper, "to-upper"),
    (HiFunToLower, "to-lower"),
    (HiFunReverse, "reverse"),
    (HiFunTrim, "trim"),
    (HiFunList, "list"),
    (HiFunRange, "range"),
    (HiFunFold, "fold"),
    (HiFunPackBytes, "pack-bytes"),
    (HiFunUnpackBytes, "unpack-bytes"),
    (HiFunEncodeUtf8, "encode-utf8"),
    (HiFunDecodeUtf8, "decode-utf8"),
    (HiFunZip, "zip"),
    (HiFunUnzip, "unzip"),
    (HiFunSerialise, "serialise"),
    (HiFunDeserialise, "deserialise"),
    (HiFunRead, "read"),
    (HiFunWrite, "write"),
    (HiFunMkDir, "mkdir"),
    (HiFunChDir, "cd"),
    (HiFunParseTime, "parse-time"),
    (HiFunRand, "rand"),
    (HiFunEcho, "echo"),
    (HiFunCount, "count"),
    (HiFunKeys, "keys"),
    (HiFunValues, "values"),
    (HiFunInvert, "invert")]
